### ISSUE TITLE
Where were the co-occurrence matrices created

### ISSUE THREAD

**Issue by don-tpanic** [LivNLP/SCL#1]
Hello Professor, 

Forgive me if it's something rather silly, but I don't seem to find where you created the co-occurrence matrices for each domain in either of the script.

Thanks

**Comment by Ramay7** [comment]
@don-tpanic 
Hello Professor,

I have met the same problem that I cannot find co-occurrance matrices. Have you solved the problem? Or have you found some other implementations of SCL and SCL-MI? 

Thanks :)

Best Regards

**Comment by don-tpanic** [comment]
> @don-tpanic
> Hello Professor,
> 
> I have met the same problem that I cannot find co-occurrance matrices. Have you solved the problem? Or have you found some other implementations of SCL and SCL-MI?
> 
> Thanks :)
> 
> Best Regards

https://github.com/yftah89/structural-correspondence-learning-SCL  Here is an implementation of SCL. I am not entirely confident this is the exact implementation as suggested on the original paper as I was getting sub-optimal performance. But it could give you some idea. I had contacted the original author of the SCL paper and he said the original code for reproducing his results is no longer available.

**Comment by Bollegala** [comment]
You do need to build the co-occurrence matrices from the Amazon multi-domain sentiment dataset given here. https://www.cs.jhu.edu/~mdredze/datasets/sentiment/
